version: "3.8"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: social_dev
    volumes:
      - pg-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db-test:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: social_dev_test
    volumes:
      - pg-db-test:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg-db:
  pg-db-test:
